<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Availability extends Model
{
    protected $fillable = [
        'doctor_id',
        'date',
        'start_time',
        'end_time',
    ];

    protected function casts(): array
    {
        return [
            'date' => 'date',
        ];
    }

    public function doctor()
    {
        return $this->belongsTo(Doctor::class);
    }

    public function appointmentSlots()
    {
        return $this->hasMany(AppointmentSlot::class);
    }

    public static function overlapsExisting(int $doctorId, string $date, string $start, string $end, ?int $ignoreId = null): bool
    {
        $startFormatted = \Illuminate\Support\Carbon::parse($start)->format('H:i:s');
        $endFormatted = \Illuminate\Support\Carbon::parse($end)->format('H:i:s');

        return static::where('doctor_id', $doctorId)
            ->whereDate('date', $date)
            ->when($ignoreId, fn ($q) => $q->whereKeyNot($ignoreId))
            ->where('start_time', '<', $endFormatted)
            ->where('end_time', '>', $startFormatted)
            ->exists();
    }

    /**
     * Generate fixed-length appointment slots for this availability window.
     */
    public function generateSlots(int $slotMinutes = 30): void
    {
        $dateStr = \Illuminate\Support\Carbon::parse($this->date)->format('Y-m-d');
        $start = \Carbon\Carbon::parse($dateStr.' '.$this->start_time);
        $end = \Carbon\Carbon::parse($dateStr.' '.$this->end_time);

        while ($start->copy()->addMinutes($slotMinutes)->lte($end)) {
            $slotEnd = $start->copy()->addMinutes($slotMinutes);

            $existing = AppointmentSlot::where('doctor_id', $this->doctor_id)
                ->whereDate('date', $dateStr)
                ->where('start_time', $start->format('H:i:s'))
                ->first();

            if ($existing) {
                if ($existing->availability_id !== $this->id) {
                    throw new \RuntimeException(
                        "Slot collision at {$start->format('H:i')} for doctor {$this->doctor_id} on {$this->date->format('Y-m-d')}: already generated by availability #{$existing->availability_id}."
                    );
                }
            } else {
                $this->appointmentSlots()->create([
                    'doctor_id' => $this->doctor_id,
                    'date' => $this->date->format('Y-m-d'),
                    'start_time' => $start->format('H:i:s'),
                    'end_time' => $slotEnd->format('H:i:s'),
                    'status' => 'available',
                ]);
            }

            $start = $slotEnd;
        }
    }
}
